### ISSUE TITLE
Go 1.12

### ISSUE THREAD

**Issue by oherych** [valyala/fasttemplate#16]
He. Why do you have the minimum required version `Go 1.12`?

**Comment by povilas-st** [comment]
This has caused the echo framework (https://github.com/labstack/echo/blob/master) to become unusable with Go 1.11, because it has fasttemplate as a dependency.

**Comment by valyala** [comment]
Tried removing the dependency in [v1.0.1](https://github.com/valyala/fasttemplate/tree/v1.0.1). @oherych  and @velnez , could you confirm that the issue is fixed after upgrading `fasttemplate` to `v1.0.1`?

**Comment by oherych** [comment]
sorry, I don't have access to this source code any more.  Lets close it. Thanks
