### ISSUE TITLE
strings.Replacer drop in replacement

### ISSUE THREAD

**Issue by DoubleDi** [valyala/fasttemplate#20]
Hey @valyala! Thanks for the great lib!
We have a lot of code, for url macros substitutioning with strings.Replacer. When we realised, that it was using too much memory, we chose your lib to optimize the performance. 

But the main problem is that we are using different replacers not once on a single template string, but many times. 
Example
```
a := "{a}{b}"
r := strings.Replace(a, "{a}", "1") // r == 1{b}
...(other part of code)...
r = strings.Replace(r, "{b}", "2") // r == 12
```
with replacers all is fine, but your engine skips the unknown values by default. 
```
a := "{a}{b}"
r := fasttemplate.ExecuteString(a, "{", "}", map[string]intreface{}{"a": "1"}) // r == 1
...(other part of code)...
r = fasttemplate.ExecuteString(r, "{", "}", map[string]intreface{}{"b": "2"}) // r == 1
```

We made a wrapper for your lib, that fixes that. It actually just changes a little the `stdTagFunc`. 

What do you think of making this the default behaviour to make the engine more compatible with strings.Replacer? PR will be made on having your approve

**Comment by valyala** [comment]
I think it would be better creating a new function with behavior aligned with `strings.Replacer`, since changing behavior for the existing function can break existing users' code.

**Comment by valyala** [comment]
The pull request #23 has been added into [v1.2.0](https://github.com/valyala/fasttemplate/tree/v1.2.0). Closing this feature request as done.
